### PR TITLE
Dev 1.35.0

### PR DESCRIPTION
**Pull request by cubicgraphics**
Added values to the info part of the status api
        `int maxPlayers` - Max players supported per server lobby
        `bool supportsPPModifiers`
        `bool supportsPPDifficulties`
        `bool serversupportsPPMap`    
(PP meaning per player)

### CODE REVIEW

**Comment by cubicgraphics** [comment]
renamed `bool serversupportsPPMap` to `bool supportsPPMap`

**Comment by roydejong** [comment]
@cubicgraphics I've merged the info data/endpoint into status. I don't really see the value in having two separate endpoints here, and seemingly arbitrarily splitting config data between the two. As far as I know `/info` has not yet been used anywhere. LMK if you see an issue with this

**Comment by cubicgraphics** [comment]
Yep, I'm fine with this.

**Comment by cubicgraphics** [comment]
If there is any more values you think should be added please do so

**Comment by roydejong** [comment]
I've written up some documentation on multiplayer status handling / fields, so we have a common standard for master servers: 
https://github.com/Goobwabber/MultiplayerCore/wiki/Multiplayer-Status

I've also gone ahead and added the new fields to MpStatusData in https://github.com/Goobwabber/MultiplayerCore/pull/49/commits/3a7e582eaa71076866d2e0990b4c9363fda0c399 so it will be available for mods

If there's any other fields we want to introduce it'd be good to try and get them in before the upcoming release cycle

**Pull request merged**
